contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - prometheus-node-exporter
    - busybox

accounts:
  groups:
    - groupname: node_exporter
      gid: 65532
  users:
    - username: node_exporter
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/node_exporter

archs:
  - x86_64
  - aarch64
