contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - nginx

accounts:
  groups:
    - groupname: nginx
      gid: 65532
  users:
    - username: nginx
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /s6
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
  - path: /var/lib/nginx
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true
  - path: /run/nginx
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o755
    recursive: true
  - path: /var/log/nginx
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o755
    recursive: true
  - path: /var/lib/nginx/tmp
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o755
    recursive: true

entrypoint:
    command: /usr/sbin/nginx 

cmd: -c /etc/nginx/nginx.conf -g "daemon off;"

stop-signal: SIGQUIT

archs:
  - x86_64
  - aarch64
