contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - busybox
    - opensearch-2

accounts:
  groups:
    - groupname: opensearch
      gid: 65532
  users:
    - username: opensearch
      uid: 65532
  run-as: opensearch
  recursive: true

environment:
  JAVA_HOME: /usr/lib/jvm/openjdk-jre/

entrypoint:
  command: /usr/bin/docker-entrypoint.sh

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/opensearch/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/opensearch
