contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - traefik

accounts:
  groups:
    - groupname: traefik
      gid: 65532
  users:
    - username: traefik
      uid: 65532
  run-as: traefik

paths:
- path: /tmp
  type: directory
  permissions: 0o777

entrypoint:
  command: /usr/bin/traefik

archs:
  - x86_64
  - aarch64
