contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - kube-state-metrics
    - busybox

accounts:
  groups:
    - groupname: kube-state-metrics
      gid: 65532
  users:
    - username: kube-state-metrics
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/kube-state-metrics

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/kube-state-metrics/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/kube-state-metrics