contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - fluent-bit

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: nonroot

paths:
  - path: /var/lib/fluent-bit
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

entrypoint:
  command: /usr/bin/fluent-bit

archs:
  - x86_64
  - aarch64
