issuer: https://token.actions.githubusercontent.com
subject: repo:jdolitsky/images:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: jdolitsky/images/.github/workflows/tf-lockfile-update-bot.yaml@refs/heads/main
  #job_workflow_ref: chainguard-images/images/.github/workflows/tf-lockfile-update-bot.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
