apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: is-signed
spec:
  images:
    - glob: ghcr.io/jdolitsky/*
  authorities:
    - name: keyless-authority
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/jdolitsky/images/.github/workflows/release.yaml@refs/heads/faster-policy-check-testing
      ctlog:
        url: https://rekor.sigstore.dev
