name: Terraform lockfile update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: github.repository == 'chainguard-images/images'

    permissions:
      contents: read # To clone the repo
      id-token: write # To gitsign and federate

    steps:
    - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: lockbot

    # TODO: use ${{ steps.octo-sts.outputs.token }} for git commit
    - name: Run tfupdate and open PR if any diff
      shell: bash
      run: |
        set -x
        make tfupdate

        // zipDataToH1Hash is a helper function that calculates the h1 hash value from
// bytes sequence of the provider's zip archive.
func zipDataToH1Hash(zipData []byte) (string, error) {
	// The h1 hash value in .terraform.lock.hcl uses the same hash function as go.sum.
	hash, err := dirhash.HashZip(tmpZipfile.Name(), dirhash.Hash1)
	if err != nil {
		return "", fmt.Errorf("failed to calculate h1 hash: %s", err)
	}
	return hash, nil
}

        if git diff-index --quiet HEAD --; then
          echo "No git diff detected. Exiting."
          exit 0
        fi
        # TODO: open PR with diff here
