on:
  pull_request:
jobs:
  presubmit-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - id: files
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
      with:
        format: csv
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all }}
        melange-mode: none
  presubmit-build:
    runs-on: ubuntu-latest
    needs: presubmit-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Ensure image has tests
        if: matrix.testCommandExe == ''
        run: |
          echo "Error: ${{ matrix.imageName }} image is missing tests."
          exit 1
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup:
    runs-on: ubuntu-latest
    needs: presubmit-build
    steps:
      - run: |
          echo "all matrix jobs completed"
